repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
    name: fix trailing whitepace
  - id: end-of-file-fixer
    name: fix eof
  - id: check-yaml
    name: check yaml
  - id: check-added-large-files
    name: check added large files
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.12.0
  hooks:
  - id: reorder-python-imports
    name: reorder python imports
    args: ['--add-import', 'from __future__ import annotations']
- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.1.0
  hooks:
  - id: add-trailing-comma
    name: add trailing commas
    args: ['--py36-plus']
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args: ['--py312-plus']
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    args: ['--max-line-length', '88']
    additional_dependencies:
    - flake8-bugbear
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.1
  hooks:
  - id: mypy
    args: ['--strict']
